### ISSUE TITLE
Review existing agile documents for shareability

### ISSUE THREAD

**Issue by afomi** [18F/agile#102]
# Goal

In effort to prevent `dead-end` documents (docs that are created, are valuable, but end up orphaned simply because they were not visible or on a well-worn path); review existing agile docs in Google docs and other silos, and assess each document for:

* is it valuable to the public?
* is it valuable to other agile practitioners in gov?
* does this document still need to exist?
  * is it in progress?  `draft` 
  * a valuable (meaningful) artifact?  `write up of a shareable agile pattern`
  * or the equivalent of a digital sketch that is not actionable and can be discarded)  `a draft superseded by another version/fork`

### Acceptance

* fewer `dead-end` documents exist

### Notionally

* more valuable content lives online (and is thus iterate-able online)
* more clarity on what agile documents that exist (and who they are for)
* more understanding about how information is (and isn't shared)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
