### ISSUE TITLE
Create an email alias for all the members of the Agile Guild

### ISSUE THREAD

**Issue by afomi** [18F/agile#103]
# User Story

As a member of the Agile Guild
I want a reliable way to email all members of the Guild
So that I can efficiently communicate with colleagues

# Acceptance

Given an alias exists
And the email for each member is added to the alias
When I email agile-guild@example.com
Then all email addresses receive an email

# Consideration

It seems that setting up an email alias would be a common task across any guild, and therefore would be a good task to add to a common Process document (a'la Checklist Manifesto)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
