### ISSUE TITLE
Publish a Calendar for the Agile Speaker Series

### ISSUE THREAD

**Issue by afomi** [18F/agile#104]
### User story

As a guild co-lead
I want to be able to share a calendar of Speakers
So that I can better schedule speakers by letting them know available dates

### Acceptance

Given a calendar exists with as many Speaker Events as we know about
And have tentatively marked out speaker slots for every 6 weeks
When I view the calendar
Then I can view all events

**Comment by afomi** [comment]
Post these events on the existing TTS Guilds and Meetings calendar.

Denote these events with "Speaker Series" in the title

**Comment by afomi** [comment]
<img width="764" alt="speaker-series-calendar" src="https://user-images.githubusercontent.com/67984/54046973-afaaa800-418a-11e9-9d94-743d64c456ff.png">

https://calendar.google.com/calendar/r/search?q=AGILE%20GUILD%20SPEAKER%20series

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
