### ISSUE TITLE
Update Agile Approach Description to Include Acquisitions

### ISSUE THREAD

**Issue by mheadd** [18F/agile#105]
18F's current approach to agile projects is outlined [here](https://github.com/18F/agile/blob/18f-pages/pages/18f-agile-based-project-approach.md). As written, this approach seems to include instances where 18F teams build digital products (e.g., "when we build..."), but is mostly silent on how an agile team handles engagements where a procurements is conducted.

It would be helpful if this description could be expanded to accommodate instances where 18F is engaged on an acquisition consulting or assisted acquisition engagement.

cc: @AshleyO85 @hannahkane

**Comment by hannahkane** [comment]
How can I help? @mheadd - were you going to take a first crack at this? Happy to review/provide input.

**Comment by mheadd** [comment]
@hannahkane For now, just wanted to open the issue to make sure we didn't lose sight of this.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
