### ISSUE TITLE
Move to 18F Pages Style

### ISSUE THREAD

**Issue by wslack** [18F/agile#11]
It looks like this repo isn't using the style of other guides (like having a link to the repo in the footer). Unsure how to fix, but wanted to flag.

**Comment by ultrasaurus** [comment]
@wslack thanks for flagging!  It's cuz this repo pre-dated (and was the genesis of) the 18F Guide style and we never refactored to adopt it.  Good to have it officially on our "to do" list

**Comment by bplmp** [comment]
I have an open pull request exactly for this issue here:
https://github.com/18F/agile/pull/10
I might have done something wrong and you guys might have not got the request (I'm kind of new to collaborating like this) but hope it is of use!

**Comment by mbland** [comment]
Just commented on #10, @bplmp, thanks!

**Comment by wslack** [comment]
@bplmp thank you! I didn't notice that. You're in good hands with Mike and the PR was submitted correctly, though I see he has a comment.

**Comment by porta-antiporta** [comment]
Believe this has been addressed.

**Comment by wslack** [comment]
@porta-antiporta actually I don't think so but not a huge deal
