### ISSUE TITLE
Apply isildurs-bane template to repo

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/agile#115]
This issue is similar to https://github.com/18F/development-guide/issues/184 which was resolved by the set of changes in https://github.com/18F/development-guide/pull/194

Some related discussion in #agile is at https://gsa-tts.slack.com/archives/C03JN1M6S/p1601056732006400

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
