### ISSUE TITLE
Create agile health survey

### ISSUE THREAD

**Issue by meiqimichelle** [18F/agile#25]
In our Jun 17 guild meeting, Robb suggested creating a very lightweight survey to measure agile health across the org based on an approach in _Practices of an Agile Developer_.

It has "how you know you're doing it right" with a "feels like" section. Much of it is not developer-centric so it would be good for the whole org. We could take a few of the "feels" from the book and use a simple scale. The book also already has suggested solutions for issues, super helpful.

**Comment by mogul** [comment]
Lots more here: https://trello.com/c/eiBQSFkX/4-adopt-periodic-squad-health-check-model-to-determine-needs-for-coaching-process-improvment
