### ISSUE TITLE
a test for if an agency stakeholder is really willing to do agile

### ISSUE THREAD

**Issue by ultrasaurus** [18F/agile#3]
Some suggested language:

Agile projects are goal-driven, not feature-driven.  You must be willing to articulate a goal that is written in terms of outcomes for the users of the service, then establish a way to measure whether a service meets the goal and guage the success of the product based on qualitative and quantitative assesment of whether that goal is met.  You must be willing to have a subset of your target audience use the product before it is ready, and agree that such as process is the only true way of assessing readiness.

**Comment by ultrasaurus** [comment]
this is a test of our notification system

**Comment by ultrasaurus** [comment]
this is a test of the github notification system

**Comment by mtorres253** [comment]
Possibly link to sections of the playbook? Or add some things to the playbook?
https://pages.18f.gov/partnership-playbook/4-agile/

**Comment by OpenGlobe** [comment]
Just FYI @ultrasaurus - I've added this to the blog post Alan and I are working on as a quote from you - I think it's a good statement, I'll share a draft when ready to make sure it works for you and you agree it fits.

**Comment by porta-antiporta** [comment]
Closing given new guide just being released which de-emphasizes agency readiness in the agile guide.  Agency readiness is kept to the [parnership principles](https://18f.gsa.gov/partnership-principles/).
