### ISSUE TITLE
Identify someone to sort out training process

### ISSUE THREAD

**Issue by meiqimichelle** [18F/agile#31]
Set a process for connecting guild members with training/shadowing AgileBPA workshops/meetings.

**Comment by meiqimichelle** [comment]
Background notes:
- Sync up with Alan A on agile acquisition workshops: “Right now, Alan Atlas is helping with workshops. Normally, we meet with clients who show up with a big waterfall list of things. He will do like 2 days of workshops -- first day, present agile techniques, second day, try to apply this to the contract. Output of the RFP sessions we hope is a good agile RFP.”
- Can those provide funding for an extra person to sit in?
- Can we use training money for this?

**Comment by nikzei** [comment]
Chatted with Alan Atlas about this - he said that there is no consolidated place where we keep track of workshops. He suggested conducting searches on Slack. 

Maybe, to start, we should just put it on the calendar to do regular weekly call out for upcoming workshops in the #workshops channel and with particular individuals that we know are doing workshops.

**Comment by nikzei** [comment]
In guild meeting, discussed that having individuals sit in on workshops held by other teams for the purpose of learning might not work with new weekly billing practice, which requires us to bill 32 hours to one project (so the individuals sitting in would not be able to bill the hours spent to a project other than his/her primary project).

We'll start this by reaching out in channels and to particular individuals and try to get a list going of agile-related workshops being help by 18F. We'll start small and simple, take it from there.
