### ISSUE TITLE
Update favicon for the Agile Guide

### ISSUE THREAD

**Issue by allalala** [18F/agile#52]
![image](https://user-images.githubusercontent.com/6518236/42234431-8b37fa76-7ec2-11e8-9e64-c999bb9e8c36.png)

**Comment by porta-antiporta** [comment]
Root cause to an old gem being used for the 18f-style-guide. h/t @stvnrlly.

Working through it, but to rebuild using newer gems have to first upgrade my version of Ruby, which is proving...challenging.

**Comment by porta-antiporta** [comment]
resolved by #55
