### ISSUE TITLE
FY Q4 (Jul-Sep) guild bulletin

### ISSUE THREAD

**Issue by suprenant** [18F/agile#61]
Send out once every couple months/quarter
Talking points

We have good discussion in meetings but don’t necessarily communicate out what we learned/discussed
Help others benefit from that discussion
Send out once every couple months/quarter
Talking points
Helpful to recruit folks to meeting, potentially - market/publicize 
Can point to resources/artifacts – here are some things we used, this is what we discussed
Good to be short – just a few lines from each meeting
Send out once every couple months/quarter

Writing Lab issue:
https://github.com/18F/writing-lab/issues/405

**Comment by suprenant** [comment]
As discussed in our leads meeting, we'll talk to the team about what we're after and see who may be able to help with our inaugural bulletin.

**Comment by porta-antiporta** [comment]
I actually got a start on it!!! woohooo!!!!  https://docs.google.com/document/d/1SNhcxSNJKWEiHp1PqeXCikUi_lz71WhmUwiP1qoST9g/edit#heading=h.rfh7evodobzw
Will be posting it to the guild channel as well to see if there's anyone that wants to take on a bullet point.

Note: making an executive decision to have this bulletin cover from May - Sep (given that's when @suprenant became co-lead).

**Comment by suprenant** [comment]
I drafted a section on PopcornFlow.

**Comment by suprenant** [comment]
I'll do one more review. Porta will send this to the writing lab by Tuesday afternoon so we can review and ship.

**Comment by suprenant** [comment]
@porta-antiporta any update on the guild bulletin?

**Comment by afomi** [comment]
@porta-antiporta - is there anything to add before moving forward toward publication?

**Comment by porta-antiporta** [comment]
whoa, sorry didn't see these pings.  i say let's go ahead and :shipit:

**Comment by porta-antiporta** [comment]
the writing lab hasn't gotten to it, but i don't think that's a must for publication.  do y'all want to send it out? given i'm no longer a lead, figure it'd be good for TTS to get it from a lead.

**Comment by porta-antiporta** [comment]
Aight cleaned up the doc, added a link to the meeting in the repo as part of #94.  Looking for your 👍 @suprenant and @afomi

**Comment by suprenant** [comment]
Thanks @porta-antiporta. I think it still needs to be edited down for length/tone, but I agree we want to get this out. @afomi let's discuss and maybe pair on this the next time we sync.

**Comment by suprenant** [comment]
As an update, I am picking this up and will revise and ship.

**Comment by suprenant** [comment]
Sent to tts@gsa.gov. Waiting for this to come through.

**Comment by suprenant** [comment]
Shipped!
