### ISSUE TITLE
Quarterly guild retro and/or pulse survey

### ISSUE THREAD

**Issue by suprenant** [18F/agile#62]
So we know how we're doing...

Conduct quarterly pulse survey to see how we’re doing
NEO one is good
Retro at some regular cadence?

What are we doing here? What do you want out of this?
How are we doing? 
Check in with Alan Atlas, Bret

**Comment by afomi** [comment]
@suprenant - any thought on Acceptance criteria?

The value of getting feedback is good.
I'd like there to be a sketch about how to get from feedback to action change too.

I could see this being a quarterly Survey/Form - which would need a v1 draft.

**Comment by suprenant** [comment]
@afomi let's discuss. I feel there's probably room for both a survey to the guild members as well as some sort of retro – maybe with the members (in place of a form) or, perhaps better yet, just with the guild leads (maybe inviting others that would want to attend but not taking up one of our more precious biweekly meetings).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
