### ISSUE TITLE
Guest speaker approach

### ISSUE THREAD

**Issue by suprenant** [18F/agile#63]
What are we after:

 - Deepen collective learning, inspiration
 - Potentially increase attendance (esp. other parts of TTS aside from 18F)
 - Chance to talk to people about our challenges
 - Help give folks opportunity to talk internally to support eventual external speaking. Tap our internal wisdom

Possible formats: 

 - Presentation
 - Fishbowl discussion

Topics:

 - DevOps (do something w/DevOps guild)

Speakers:

 - Could be external or internal

Who has spoken before:
 - S. Andrews
 - Simon Wardley

Cadence:

 - Thinking every 1-2 months to start, depending on availability 

Implementation steps:

 - [x] Reach out to @vicuk to see if we can learn about what strategy has been doing, what's been working for them
 - [x] Check to see what topics/people might be useful with team (via [Mural](https://app.mural.co/t/gsa6/m/gsa6/1542669995395/b689a3eea32ffaec14670da8f0938aaa18501a76)): 
(https://docs.google.com/document/d/1rMRJa1YJI4YHPUcKJDNbMkFYocMJw3R_0T6FnXiPiD0/edit) 
 - [x] Create a [scheduling spreadsheet](https://docs.google.com/spreadsheets/d/1hMjs_sAOLzTj39g-kuptZZxkG-Xmfe-FlN0Kb9zfqQI/edit#gid=0) with folks we want to contact and available speaking slots
 - [x] Draft [outreach email copy](https://docs.google.com/document/d/1rMRJa1YJI4YHPUcKJDNbMkFYocMJw3R_0T6FnXiPiD0/edit)

**Comment by ecayer** [comment]
I know Bob Moesta and John Cutler. Bob seems to overcommit to everything, so he's hard to pin down.

**Comment by ecayer** [comment]
I also like Uchenna's idea of approachingthis  by topics we're interested in. (I know it's implicit in the list of people, but we can always turn that around) If we have TOPIC, then a list of possible speakers, that might help us target our search and generate some new ideas!

**Comment by suprenant** [comment]
Elizabeth and I discussed this this afternoon and will follow up on next steps, including a discussion with the guild to see what topics/people they'd be interested in hearing from, over the next two weeks.

**Comment by suprenant** [comment]
I am drafting the outreach email, which is linked above.

**Comment by suprenant** [comment]
OK @ecayer, I have drafted the outreach email copy (linked above). 

It could probably use one more pass but is close to what I think we'll be after. Would you like to take a look and leave any comments/suggestions?

**Comment by suprenant** [comment]
@ecayer FYI I moved our notes on the speakers series over to our leads doc here to keep our team meeting notes cleaner: https://docs.google.com/document/d/11w5VA-PY-KuBx7sLBJyjDdAnuTQPGR9otx9eRjTyYtQ/edit#heading=h.5mibbj2v3qka

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
