### ISSUE TITLE
Discussion: Scaling Agile

### ISSUE THREAD

**Issue by suprenant** [18F/agile#65]
What we're after: 
 - Our community has expressed interest in this, particularly expression curiosity about agencies using SAFe. Partner may have mentioned SAFe, may have needs to scale agile
 - Exposure for guild
 - Could give us content, something to memorialize (not seeing much recently, older cloud.gov, maybe FEC)
 - We want to steer away from discussing specifically SAFe, rather agility at scale

Some smaller chunks we could look at:
 - Agile program management
 - Multiple vendors, multiple teams (what are the good things that seem to work, SAFe, LeSS, DAD)
 - Step 0 in scaling
-- Learning how to avoid it
-- Steve Denning (Andrew to follow up)
 - DA Decision framework

Possible formats: 
 - Training
 - Coaching
 - Unconference / open space : virtually
 - Failures – when does agile at scale go bad?

Possible people who can represent:
 - Bret, Alan A., Cata, Hopson indicated interest
 - Prisby or someone else from Login.gov
- Porta's experience with scaled projects

People we can speak to about ideas:
 - Uchenna (Porta to check)

Maybe/later:
 - Federalist (Eddie)

Notes/other considerations
 - Marketing
 - yeah that SAFe one i think would make a good “marquee” agile guild event
 - Good to have other members contribute
 - Solicit questions beforehand
 - Memorialize somehow

More context here:
https://docs.google.com/document/d/11w5VA-PY-KuBx7sLBJyjDdAnuTQPGR9otx9eRjTyYtQ/edit#heading=h.wpfgksukm3w4

**Comment by porta-antiporta** [comment]
Notes from 8/24 guild meeting.

* Want to steer away from discussing specifically SAFe, rather agility at scale
* But even agility at scale is too large a topic so let's look at some smaller chunks:
    - Agile program management
    - Multiple vendors, multiple teams. (what are the good things that seem to work
SAFe, LeSS, DAD)
    - Step 0 in scaling
         -- learning how to avoid it
         -- Steve Denning 
    - DA Decision framework

* 2 formats for this kind of thing (long term)
-- training format
-- coaching format
-- unconference / open space : virtually

* But how do you market something like ^^?  That's the event the guild would target to have.
   - Failures
      -- When does agile at scale go bad

How much useful experience does the guild have to put on something like this?
-- Uchena Moka

**Comment by suprenant** [comment]
From our leads sync – Porta to follow up with Uchenna on possible folks she may know who can speak to this, and I'll look up the Steve Denning angle.

**Comment by suprenant** [comment]
@porta-antiporta FYI, I cleaned up the issue as discussed.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
