### ISSUE TITLE
Article/post/book club

### ISSUE THREAD

**Issue by suprenant** [18F/agile#66]

**Comment by suprenant** [comment]
Our cybersecurity group is doing this. Could be an interesting model for us.

**Comment by afomi** [comment]
I've seen many reading lists online, but not sure about what's linkable or not.

A Form for submissions + shared Spreadsheet to hold the data would be an 👌 v1

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
