### ISSUE TITLE
Increased attendance at guild meetings

### ISSUE THREAD

**Issue by suprenant** [18F/agile#67]
See if folks know how to find us
Guild invitations can be tricky
Invite folks directly?

Let TTS know we are here
Reach out to OPP, Acq., PIF, etc. leads
Reach out to people, grow membership
Reach out to every new hire
Reach out to all new hires from last 365 days

**Comment by porta-antiporta** [comment]
I would say that thus far, the most success we've had in the previous quarter was having folks who had just joined TTS attend the guild meetings.

Also, was thinking that if we can get traction on office hours, it would be good way to have folks become more aware of the guild.

**Comment by porta-antiporta** [comment]
Propose closing this issue given that I think there's a definite influx of active guild members.  Focusing on the other issues in the backlog will continue to keep the membership active IMHO, so no need for a separate tracker.  thoughts @suprenant @afomi ?

**Comment by suprenant** [comment]
+1 – this feels like more of an ongoing goal/objective for now. Closing this up.
