### ISSUE TITLE
TTS State of Agile 2019

### ISSUE THREAD

**Issue by suprenant** [18F/agile#70]
What about doing our own report?

https://gsa-tts.slack.com/archives/C03JN1M6S/p1525964097000673
https://explore.versionone.com/state-of-agile

**Comment by afomi** [comment]
I think this is an interesting idea, but curious about the cost, effort, and maintenance.

* What is the unique value of publishing our own?
* Who is the audience?
* What is the objective?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
