### ISSUE TITLE
Strengthen connections with other communities of practice

### ISSUE THREAD

**Issue by suprenant** [18F/agile#73]
Agile Community of Practice 
How to help organize/contribute (GAO, OMB), has about 200 people
https://digital.gov/communities/agile-lean/
https://www.agilegovleaders.org/agl-establishes-non-profit-association-serve-government-innovation-community/

**Comment by afomi** [comment]
Is there a roster of members? I'd like to better understand Guild vs Community of Practice membership.

**Comment by afomi** [comment]
cc @ecayer

**Comment by suprenant** [comment]
@afomi following up here. I don't know offhand of a roster (we don't have one for the guild as it's more of an "attend and you're a member" sort of thing). We could follow up with the other community to see if they have something.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
