### ISSUE TITLE
10x submission

### ISSUE THREAD

**Issue by suprenant** [18F/agile#74]
_Guilds may propose projects via 10X and other avenues, which would then receive budget if approved._

Ideas:
 - Agile Guild notes on Agile Industrial Complex
https://docs.google.com/document/d/1pbq7swca7DRUygJFL6ovYpcTl6Rep6ABOQFN4IZSa5g/edit#heading=h.un9hcm4iand

**Comment by suprenant** [comment]
@porta-antiporta FYI, I added this issue in case we think of a guild idea we'd want to submit for 10x.

**Comment by afomi** [comment]
@suprenant - okay to close?
