### ISSUE TITLE
New Agile Guild lead

### ISSUE THREAD

**Issue by suprenant** [18F/agile#77]
What we're after:
 - So we can continue our guild leadership, we want to find a replacement for @porta-antiporta :pour-one-out:

Implementation steps:
 - [x] Set up Google Form
 - [x] Solicit nominations
 - [x] Notify nominees of nomination, check interest in interviewing
 - [x] Schedule/conduct interviews
 - [x] Confer and select lead (Andrew/Porta)
 - [x] Notify all nominees 
 - [x] Announce to TTS!

**Comment by suprenant** [comment]
@porta-antiporta as discussed, if you hit me up with the materials we used last time, I can review/revise them and coordinate with Jacqueline on next steps.

**Comment by porta-antiporta** [comment]
I :slacked: you what I have re: guild lead selection.

**Comment by suprenant** [comment]
Picking this back up....

**Comment by suprenant** [comment]
We are currently accepting nominations and will reach out to nominated folks next week to assess their interest and schedule interviews.

**Comment by suprenant** [comment]
I have notified folks who have been nominated and will be scheduling interviews over the next two weeks.

**Comment by suprenant** [comment]
As an update, we have interviews scheduled with candidates next week. I still have not heard back from one candidate to determine whether or not they are interested and will follow up with them.

**Comment by suprenant** [comment]
As an update, we rescheduled an interview for the guild lead role, so we now expect to have the next lead selected by the week after Thanksgiving – the week of 12/3.

**Comment by suprenant** [comment]
Waiting on some TTS administrivia.

**Comment by afomi** [comment]
@afomi selected as new lead Agile Guild. Closing 👋
