### ISSUE TITLE
Situational Awareness 101 presentation

### ISSUE THREAD

**Issue by suprenant** [18F/agile#78]

**Comment by afomi** [comment]
I'll plan to give a `Situational Awareness 101` presentation. Though I'm open-to and seeking Feedback regarding topics or scenarios people would also like discussed.

I'll work with @suprenant on a date.

**Comment by afomi** [comment]
My understanding is Simon Wardley recently gave a talk here. 🎉 

He's much more suited to give the talk, and thus fulfills the intent of this Issue.
So, I'll re-focus on ensuring that his talk is available to view/share.

**Comment by suprenant** [comment]
Sounds good to me. I know there is a recording of that Wardley talk – I believe 18F Strategy may have shared that out. 

Given what you've got here and that we're also planning work for a speaker series, I feel we can move this to done/close this up once we've made sure the Wardley talk is available.

**Comment by afomi** [comment]
I was able to locate the video in #strategy. Closing.
