### ISSUE TITLE
DAP integrated

### ISSUE THREAD

**Issue by afomi** [18F/agile#79]
per https://github.com/18F/agile/issues/49#issuecomment-427618732, understanding the traffic to the site can help inform future development and maintenance of this site.

# Story

As agile.gov Admin,
I want to understand traffic patterns on the site
So I can make more informed decisions regarding the website as a product.

# Acceptance

 - [ ] Given a user visits agile.18f.gov, then I can see a real-time user in Analytics.

**Comment by afomi** [comment]
see https://github.com/18F/agile/pull/92

**Comment by suprenant** [comment]
From our sync, Ryan to take a look at how to access the data we're after here.

**Comment by afomi** [comment]
@suprenant - I created https://github.com/18F/agile/issues/93 to track the work around Reporting. Closing.
