### ISSUE TITLE
modularcontracting agile content merged with Agile Guide

### ISSUE THREAD

**Issue by porta-antiporta** [18F/agile#82]
*Full background*: https://gsa-tts.slack.com/archives/C03JN1M6S/p1539812295000100

Quick synopsis: https://modularcontracting.18f.gov/agile-development/ contains content that will shortly no longer be easily available to the public.  The guild should review and find a path forward to keep that content available (perhaps in our agile guide).

Note:  the site may go down, but the repo should be available in perpetuity https://github.com/18F/Modular-Contracting-And-Agile-Development/.

**Comment by mheadd** [comment]
Wanted to note that the content, as originally written, was more geared toward our work with state governments. It might be good to replace references to "state" with the more generic "government" or "agency" when this content is moved to a new location.

**Comment by hannahkane** [comment]
@porta-antiporta - I can take a crack at this, but would you prefer to wait until the new guild lead starts? If okay to start now, should I go ahead and file a PR for someone to review, or would it be better to add suggestions to a gDoc (is there one for the site content?)?

**Comment by porta-antiporta** [comment]
@hannahkane no need to wait.  we welcome PRs, would love the review comments to be more visible (which wouldn't be the case via gDoc).

**Comment by suprenant** [comment]
Thanks @porta-antiporta @hannahkane – I think we're done here. Porta, if that's the case, can you accept this issue?

**Comment by porta-antiporta** [comment]
🎉
