### ISSUE TITLE
Trello board cleaned/decommissioned 

### ISSUE THREAD

**Issue by suprenant** [18F/agile#86]
https://trello.com/b/tPkdInLD/18f-agile-guild

**Comment by suprenant** [comment]
Requested that we close this here: 
https://gsa-tts.slack.com/archives/C055J0BL0/p1542668035030000

Good catch @ecayer !

**Comment by suprenant** [comment]
This is now done.

![screen shot 2018-11-19 at 5 45 02 pm](https://user-images.githubusercontent.com/1452369/48742030-dddb9a80-ec22-11e8-819b-7564bcdadae8.png)

**Comment by afomi** [comment]
✅
