### ISSUE TITLE
Guest speaker (John Cutler)

### ISSUE THREAD

**Issue by suprenant** [18F/agile#91]

**Comment by suprenant** [comment]
Elizabeth is :making-this-so: for Friday, 12/14!

Some notes from our 12/3 meeting here:
https://docs.google.com/document/d/1pbq7swca7DRUygJFL6ovYpcTl6Rep6ABOQFN4IZSa5g/edit#heading=h.dpr2k0tl814l

**Comment by suprenant** [comment]
Something we may want to consider, from talking to @afomi – thoughts on making the talk public when we're done? Would John be up for that? We could possibly do this through DigitalGov. If not John, maybe we could consider this for other speakers. 

Also, from Slack, we need to figure out whether or not we need an NDA for this. Jacqueline Snee is looking into this, so we should keep in touch with her to make sure that question is resolved soon.

**Comment by suprenant** [comment]
Elizabeth, a note from GSA on Meet, which we can use as Zoom backup (or maybe try it to replace Zoom): _Hangouts Meet can now host 100 total participants. Check your calendar and switch your meetings to Hangouts Meet today.__ Meet does seem to support recording, too.

**Comment by porta-antiporta** [comment]
:compliance: @porta-antiporta alert : assuming John is up for making the talk public, would need to further check in #outreach on any approvals required to "publish" it.

**Comment by suprenant** [comment]
Moving this to done. @ecayer that work with you?
