### ISSUE TITLE
Webmaster can view DAP data

### ISSUE THREAD

**Issue by afomi** [18F/agile#93]
# Story

As a Webmaster
I want to view Analytics data
So that I can analyze the data

# Acceptance

Given I can log into Google Analytics
When I set the appropriate filters (TBD)
Then I can see agile.18f.gov data

## References

Talk to Tim Lowden of DAP about how to best view data.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
