### ISSUE TITLE
Guild bulletin (Oct-Dec 2018, Jan-Mar 2019)

### ISSUE THREAD

**Issue by suprenant** [18F/agile#96]
* How do we measure this? - Emails/List
* Can folks share/sign up?

---

* R1 audience: TTS
  * Can we measure emails? Open rates? Shares?
* R2: 
  * Refine scope (tighten)
  * Consider posting online or on a blog

---

[Draft Bulletin](https://docs.google.com/document/d/12YHbzrkJfLLBsdQNB0aAlzxyEI5_82I3IBY2sZiBvrU/edit#heading=h.g705x0f73hro)

**Comment by afomi** [comment]
@suprenant and I noted that we should include things in the `Done` column in Q1 bulletin

**Comment by afomi** [comment]
Started a draft of [Q1 2019 bulletin](https://docs.google.com/document/d/12YHbzrkJfLLBsdQNB0aAlzxyEI5_82I3IBY2sZiBvrU/edit#heading=h.g705x0f73hro)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
