### ISSUE TITLE
Create a place for Agile Office Hours, Agile Resources

### ISSUE THREAD

**Issue by afomi** [18F/agile#98]
# Goal 

Create a place for Agile Office Hours, Agile Resources , Agile Guild

# Acceptance Criteria

Given User is on the agile.18f.gov website
Then User can find information about Agile Guild
AND
User can find information about Agile Office Hours 
AND
User can find information about Agile Resources

---

# Idea

Create a /community page. Reference Agile Guild, Office Hours, and how to contribute to Resources.

**Comment by afomi** [comment]
created https://github.com/18F/agile/tree/add-community-page as a start.

**Comment by afomi** [comment]
a screenshot

![cpage](https://user-images.githubusercontent.com/67984/52445860-2b102f80-2ae1-11e9-9fe0-3620933070d3.png)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
